language: node_js
node_js:
  - "6.5.0"
  - "5"
  - "node"
  - "iojs"
os:
  - linux
install:
  - npm install
  - npm run build-cli
  - ln -s /usr/bin/nodejs /usr/bin/node
  - npm link
script:
  - tyche build
  - tyche test
after_success:
  - bash <(curl -s https://codecov.io/bash)
