version: '2'
services:
  tyche-prep:
    image: node:6.4.0-slim
    volumes:
      - .:/app
      - project_node_modules:/app/node_modules
    working_dir: /app
    command: npm install
  tyche-builder:
    extends:
      service: tyche-prep
    command: npm run build-cli
volumes:
  project_node_modules:
