baseurl = "https://withinboredom.github.io/tyche/"
canonifyURLs = true
theme = "hugo-theme-learn"
languageCode = "en-us"
title = "Tyche | Bring your project fortune"

[params]
	author = "Rob Landers"
	description = "Documentation for tyche, a powerful development tool"
